### ISSUE TITLE
不支持css样式~@跳转

### ISSUE THREAD

**Issue by yy249357** [seolhw/alias-skip#21]
如css文件: 
background-image: url(~@/assets/img/h5/headerBg.png);

配置: 
"alias-skip.mappings": {
     "~@":"/src"
}
jsconfig.json中
 "paths": {
      "@/*": ["src/*"],
      "~@/*": ["src/*"]
  }
对css文件中~@插件不能生效。

**Comment by Kevint1998** [comment]
这个我推测是vscode的问题，vscode对于特定位置的链接会强制使用内置的路径解析，其他插件都会失效，例如
```css
.testcss2{
  background: url(@/img/add.png);
  "@/img/add.png"
}
```
使用ctrl+左键的方法点击链接，第一个png链接点击提示文件不存在，第二个png链接点击后打开了正确的文件
这个插件代码我本地运行了一下，发现解析的数据都是正确的，但是只要链接在url或者img的src里点击就不生效，复制出来放在外面反而能生效
